import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Great_Vibes,Nunito_Sans,Inter } from 'next/font/google';
import "./globals.css";

// 1. Configured with standard CSS variable hooks
const sansFont = Montserrat({ 
  subsets: ['latin'], 
  weight: ['800', '900'],
  variable: '--font-montserrat' 
});
const NunitoSans = Nunito_Sans({ 
  subsets: ['latin'], 
  weight: ['400','500','600','700','800', '900'],
  variable: '--font-nunito-sans'
});
const InterSans = Inter({ 
  subsets: ['latin'], 
  weight: ['400','500','600','700','800', '900'],
  variable: '--font-inter-sans'
});

const scriptFont = Great_Vibes({ 
  subsets: ['latin'], 
  weight: ['400'],
  variable: '--font-great-vibes' 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sansFont.variable} ${scriptFont.variable} ${NunitoSans.variable} ${InterSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}